### ISSUE TITLE
Add usage example please

### ISSUE THREAD

**Issue by Najsr** [ipublikuj/mqtt-client#1]
Hello, I am starting to learn Nette & PHP and I would like you to kindly ask if you would add an example how to use your library.
Thanks

**Comment by akadlec** [comment]
Surre in the future will be. But for now, use it as other nette extension.

**Comment by akadlec** [comment]
Registering in neon:

```
extensions:
	mqttClient		: IPub\MQTTClient\DI\MQTTClientExtension

mqttClient:
	broker:
		address	: %mqtt.broker.server%
		port	: %mqtt.broker.port%
	connection:
		username	: %mqtt.user.username%
		password	: %mqtt.user.password%
		clientID	: %mqtt.user.clientID%
```

and running via cli with command: `php /path/to/your/index/etc ipub:mqtt:start`
